### ISSUE TITLE
Stop command?

### ISSUE THREAD

**Issue by migmax1995** [rogro82/PiPup#64]
Is it possible to stop the popup has I created a button to trigger my cameras at will, I can start it but not stop it

**Comment by migmax1995** [comment]
I found a way by instead using a blank one with a duration of 0.1 when the state is On so it closes.

**Comment by artek79** [comment]
```
action: rest_command.pipup_text_on_tv
data:
  ip: 192.168.1.19
  message: ""
  backgroundColor: "#00FFFFFF"
  duration: 0
```
